apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: event-redis
data:
  redis.conf: |
    # Redis configuration for persistence
    dir /data
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
