# values.yaml
deployment:
  replicas: 3

service:
  type: NodePort

ports:
  web:
    port: 80
    exposedPort: 80
  websecure:
    port: 443
    exposedPort: 443

logs:
  general:
    level: INFO
  access:
    enabled: true

ingressRoute:
  dashboard:
    enabled: true

additionalArguments:
  - "--api.insecure=true"
  - "--providers.kubernetesingress.ingressclass=traefik"
