spring:
  application:
    name: event-api

  datasource:
    # url: jdbc:postgresql://postgresql.event-api.svc.cluster.local:5432/event-db
    url: jdbc:postgresql://localhost:5432/event-db
    # username: eventuser
    # password: eventpass123
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  jpa:
    hibernate:
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # Jackson configuration for JSON serialization
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    dev.peemtanapat.thaiticketmaster: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
